#!/bin/sh

JAVA_DIR=/usr/share/java
SCALAC_CLASSPATH=$JAVA_DIR/scala-library.jar:$JAVA_DIR/scala-compiler.jar

if [ -z "$JAVACMD" -a -n "$JAVA_HOME" -a -x "$JAVA_HOME/bin/java" ]; then
    JAVACMD="$JAVA_HOME/bin/java"
fi

exec ${JAVACMD:=java} ${JAVA_OPTS:=-Xmx256M -Xms16M} \
  -classpath .:$CLASSPATH:$SCALAC_CLASSPATH \
  scala.tools.nsc.ScalaDoc "$@"
